# Implementation of Matrix Vectorization

## Imports the numpy library or package 

In [7]:
import numpy as np

## Creates two different np arrays(2D matrices)

In [12]:
# Creates a 2 by 3 matrix
A = np.array([[1, -1, 0.1],
              [2, -2, 0.2]])
print(A)
print(f'The shape of A is {A.shape}')

#Creates a 2 by 4 array for the weight W
W = np.array([[3, 5, 7, 9],
               [4, 6, 8, 0]])
print(W)
print(f'The shape of W is {W.shape}')

[[ 1.  -1.   0.1]
 [ 2.  -2.   0.2]]
The shape of A is (2, 3)
[[3 5 7 9]
 [4 6 8 0]]
The shape of W is (2, 4)


## Calculates the transpose of the matrix A 

In [17]:
# Calculates the transpose of A
AT = A.T
print(f'The transpose of matrix A is \n {AT}')
print(f'The shape of the transpose of the matrix A is {AT.shape}')

The transpose of matrix A is 
 [[ 1.   2. ]
 [-1.  -2. ]
 [ 0.1  0.2]]
The shape of the transpose of the matrix A is (3, 2)


## Calculates the dot product of the matrices AT and W using numpy matmul method

In [21]:
# Calculates the dot product using matmul
z = np.matmul(AT, W)
print(f'The dot product of the matrices AT and W is \n {z}')
print(f'The shape of the dot product is {z.shape}')

The dot product of the matrices AT and W is 
 [[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
The shape of the dot product is (3, 4)


## Calculates the dot product using the @ symbol

In [26]:
# Calculates the dot product using the @ symbol
z_1 = AT @ W
print(f'The dot product of AT and W using the @ symboil is \n {z_1}')
print(f'The shape of the dot product of AT and W is {z_1.shape}')

The dot product of AT and W using the @ symboil is 
 [[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
The shape of the dot product of AT and W is (3, 4)
